[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[dev]
  port = 3001 